README.md
tests/config_test.py
tests/helper.py
tests/rules_test.py
user_sync/connector/directory.py

After much ado about git, we are ready to give it our third try, which will hopefully be the charm!

v1.1 - third try

---

user_sync/rules.py

For some reason the username and domain returned by the dashboard for a user were being ignored when constructing the `user_key`.  For federatedID users where the username is not the email, this caused the user key to differ from the one constructed for directory users.

Fix #26: use correct username and domain for dashboard users.

---

examples/example.extension.user-sync-config.yml
examples/example.extension.users-file.csv

Remove references to Adobe ID as an default new user type.
This is meant to be part of the doc of v1.1, the existing release sitting on master.

Integrate the extension example files from v1 for use on master.

---

README.md
docs/success-guide/command_line_options.md
docs/user-manual/index.md

basically updated main README, user manual, and success guide to make
it clear to the user that `--users mapped` is shorthand for including all
directory groups in the sync.

updated documentation to include instructions for "--users mapped" parameter

---

user_sync/config.py

config parser errors now have the following form:
```log
2017-03-15 14:10:50 47278 CRITICAL main - Error loading configuration
file: while parsing a block mapping
in "user-sync-config.yml", line 1, column 1
expected <block end>, but found '<block mapping start>'
in "user-sync-config.yml", line 104, column 5
```

fix for unhandled exception when slight error in config file

---

tests/config_test.py
user_sync/app.py
user_sync/config.py
user_sync/rules.py

Alters `managed_identity_types` to be `exclude_identity_types`.
This involved the following changes:
* Take out the exclude filtering on `orphan_dashboard_users`, because all of the filtering now happens in the comparison function, and it just doesn't add a user to the `orphan_user_list` if it's been excluded.
* Make sure logging isn't done of excluded users unless it would actually prevent them from being operated on.
* Remove the filtering by type that was done on creates, because creates are no longer controlled.
* Proposed to make the key go in the `dashboard` section.
There was also cleanup of a number of issues in the work on `--users mapped` and `--delete-nonexistent-users` and #49:
* Some syntax updates
* Fix the default config values to include the newly introduced values
* Fix …

First work on #87.

---

tests/rules_test.py
user_sync/config.py
user_sync/connector/directory_csv.py
user_sync/connector/directory_ldap.py
user_sync/connector/helper.py
user_sync/rules.py

* Add support for an identity_type (customizable) attribute definition a la email and others.
* Regularize spelling to 'identity_type' everywhere in directory/CSV user dictionaries.

Fix #48: Support identity type as LDAP attribute value.

---

README.md
tests/rules_test.py
user_sync/app.py
user_sync/config.py
user_sync/connector/dashboard.py
user_sync/connector/directory_csv.py
user_sync/connector/directory_ldap.py
user_sync/connector/helper.py
user_sync/rules.py

* Add support for an identity_type (customizable) attribute definition a la email and others.
* Regularize spelling to 'identity_type' everywhere in directory/CSV user dictionaries.

Issue 30/file paths in config files should be interpreted relative to the file in which they appear 2

---

user_sync/app.py
user_sync/config.py
user_sync/rules.py

The problem was that the argument value was being set in the
config_loader, but get_rule_options was not picking it up and
passing it to the rules module.

fix #134: --adobe-only-user-action exclude doesn't work.

---

user_sync/config.py

* while I was there, I also decided to fix #4, so now we have no warnings if you define but don't use the ldap or csv connectors.

fix #131 and fix #132: correctly handle default config files

---

user_sync/connector/directory_csv.py
user_sync/connector/directory_ldap.py
user_sync/connector/umapi.py
user_sync/helper.py
user_sync/rules.py

* cleaned up connector names in logging
* added filename on CSV unrecognized column error
* catch UMAPI connection failures and fail cleanly

fix #141 and other issues.

---

user_sync/config.py
user_sync/rules.py

fix #149, fix #150, fix #151, fix #153

---

docs/FAQ/index.md
docs/index.md
docs/user-manual/index.md

update docs from v2 branch

---

user_sync/app.py
user_sync/config.py

Also fixed #175 while I was in there.

Fix #159 - more secure credential handling

---

examples/config files - basic/3 connector-ldap.yml
examples/config files - basic/4 connector-csv.yml
setup.py
user_sync/app.py
user_sync/config.py
user_sync/connector/directory_csv.py
user_sync/connector/directory_ldap.py
user_sync/connector/umapi.py
user_sync/helper.py
user_sync/rules.py

With this fix, we are unicode-compliant (even in Python 2.7):
* add a `--config-file-encoding` command-line parameter, so the config files (which contain the group mapping) can contain non-ascii characters.
* add a `string_encoding` setting to the directory and ldap configurations, which controls the encoding of the input values.
* Update the sample config files to show the new settings.
* require v2.4.1 of umapi-client, to ensure that it's unicode-capable and matches its validations to the server-side validations.
* Fix #159 again by catching some edge cases around empty credential files.
* Fix #173 again by actually counting the number of primary org users read from Adobe.

Fix #167: allow non-ascii unicode chars in user and group names

---

docs/success-guide/setup_adobeio.md

Turns out there were two link. Both should be correct now.

Correct 2nd link to new Adobe I/O Authn doc

---

user_sync/connector/umapi.py

fixed #202
by changing 'all' to {'all_groups': True}
this resolved the issue. 
Tested with stage environment and it removed user group/plc from stray accounts.

Fixed --adobe-only-user-action remove-adobe-groups error

---

Makefile

fix #211 
- make will only wheel python packages in windows 64bit platform (to archive the custom windows ldap package)
- other platforms depend entirely on pex to automatically resolve dependencies

updated makefile to wheel packages only in 64 bit windows

---

examples/config files - basic/2 connector-umapi.yml
setup.py
user_sync/connector/umapi.py

Since Windows doesn't support long keystore values, we can't put the RSA private keys into the keystore.  So we have added support for encryted RSA private keys (either in files or data), and we have added a credential value `priv_key_pass` (in the clear or in the secure store) which is the passphrase to decrypt the private key.
Note that encrypted RSA private keys can be in one of two formats: PKCS#5 or PKCS#8.  (See [this article](https://github.com/kjur/jsrsasign/wiki/Tutorial-for-PKCS5-and-PKCS8-PEM-private-key-formats-differences) for examples of what they look like.)  PKCS#8 keys cannot be brute-force attacked the way that PKCS#5 keys can be, so they are a lot more secure (and allow for much simpler passphrases).  Unfortunately, our version of PyCrypto doesn't support PKCS#8 private …

Fix #198: secure RSA keys via passphrase in credential store

---

setup.py

- windows requires pycryptodome version 3.3.1
- other platforms use the latest version

workaround for pycryptodome windows path length bug

---

RELEASE_NOTES.md

Turns out #224 can be worked around, and that's preferable to using an older version of pycryptodome.

"Fix #224" by updating release notes

---

examples/config files - basic/3 connector-ldap.yml
tests/connector/directory_csv_test.py
tests/connector/directory_ldap_test.py
tests/rules_test.py
user_sync/app.py
user_sync/config.py
user_sync/connector/directory.py
user_sync/connector/directory_csv.py
user_sync/connector/directory_ldap.py
user_sync/identity_type.py
user_sync/rules.py

This changes the LDAP connector functionality to actually query for the members of each group, rather than trying to deduce them from the group membership attributes.
As corollary, this also fixes #129, because we no longer need to read the entire directory in order to make sure we've seen every member of every group.  Since we are querying for the groups directly, we don't have to read the whole directly unless we are directed to.

Fix #182: Allow indirect membership in directory groups.

---

user_sync/connector/directory_ldap.py

Fix for issue #240 
Look like this feature was implemented for CSV but not LDAP.
I partially tested it up to directory user load part of UST but unable to complete the rest due to lack of Username-Based SSO in my console.

Set domain from email when domain is not specified

---

user_sync/connector/directory_ldap.py

LDAP defines a number of special characters that must be escaped in LDAP queries:
http://www.rfc-editor.org/rfc/rfc4515.txt
The sync tool must escape any of these special characters that may be present in group names, group DNs, or anywhere else we use `string.format()` to inject dynamic values into the UST's LDAP queries.
This patch should resolve that issue.  I've tested it with special characters in group names as well as in OUs that contain groups (which shows up in the group DN).

Escape LDAP special chars

---

examples/config files - basic/3 connector-ldap.yml
examples/config files - basic/5 connector-okta.yml
user_sync/connector/directory_ldap.py
user_sync/connector/directory_okta.py

Customer requested that they want to use an alternative attribute for givenName and surname.

Added the ability to pull alternative ldap attributes for givenName, sn and c

---

user_sync/connector/directory_ldap.py

If Simple Page Mode Control ( 1.2.840.113556.1.4.319) is not supported.
Use search_page_size: 0 to disable paged results from Enterprise
Directory
#324 UST throws error 'Critical extension is unavailable' for oracle directory that does not support Simple Page Mode Control

Ability to disable paged results for Enterprise Directory

---

user_sync/app.py
user_sync/config.py

Logs showed users option "all" even when "mapped" was provided via command-line

Update config.py for #336 and app.py for #337

---

user_sync/config.py

In response to #375 
When reading from user-sync-config.yml, the adobe_only_users key was superceeded by options['users'].  Swapped comparison to take the adobe_only_users key instead if present.  
Refactored and updated logical comparison to account for both invocation defaults AND command line options when checking for the users + adobe_only_user_list parameters so that any combination of the two is disallowed.  Previously, it was possible to specify --users on the command line even if the adobe_only_user_list was specified in the configuration file (it was ignored then).  Now, the appropriate exception is thrown.

Logic correction to check for adobe_only_users (issue #375)

---

user_sync/config.py

When specify --user-filter manually via cmd line. The value does not set in console output.
When specifying --user-filter and invocation default. --user-filter does not override with arg value instead it listed config file value.
#379

Bug fix: --user-filter and config invocation default precedence

---

docs/en/user-manual/advanced_configuration.md
examples/config files - basic/1 user-sync-config.yml
examples/config files - basic/3 connector-ldap.yml
setup.py
user_sync/app.py
user_sync/config.py
user_sync/connector/directory_ldap.py
user_sync/connector/umapi.py
user_sync/rules.py

This feature adds mechanism for the sync tool to discover additional, non-mapped groups and add them to sync.  It also automatic group creation.
Configuration details can be found in `1 user-sync-config.yml`.  Additional information can be found in the "advanced configuration" manual page.
It introduces a new config option that specifies a set of one or more rules to identify and rename groups from this query to target for sync.  These groups are checked in the `memberOf` user attribute.  Rules to identify and rename these extra groups are defined in `user-sync-config.yml`.
```yaml
additional_groups:
- source: "ACL-(.+)"
target: "ACL-Grp-(\1)"
- source: "(.+)-ACL"
target: "ACL-Grp-(\1)"
```
Groups can also optionally be auto-created.  If auto-create is enabled, then any Adobe group …

Additional group discovery and creation

---

user_sync/connector/umapi.py

This will skip over the problematic users instead terminate the entire sync process.
Before:
> 2018-10-31 10:04:07 78637 CRITICAL main - Error creating umapi Action: 'Hschowãlter@adobeccetest.com': Illegal email format (must be ascii, unquoted, with no comment part)
After:
> 2018-10-31 10:06:20 78692 ERROR umapi.action - Skipping user - Error creating umapi Action: 'Hschowãlter@adobeccetest.com': Illegal email format (must be ascii, unquoted, with no comment part)
#422

Avoid App Termination when UMAPI Create Action error

---

docs/en/user-manual/advanced_configuration.md
user_sync/config.py
user_sync/connector/directory_ldap.py
user_sync/rules.py

Updates to the additional groups/auto-create features after a review by @adobeDan.  
Changes include
* Log "additional group" rule mapping
* Don't allow multiple source rules to map to same target group
* Catch regex substitution errors
* Remove some superfluous and confusing checks
I've also added secondary org support because that was missing from the original PR.
fixes #386 
fixes #392

Additional group sync updates

---

docs/en/user-manual/advanced_configuration.md
user_sync/rules.py

This feature adds support for email-type users that have different a different email address and username.  Such users can be created in the UMAPI by first creating the user with a consistent username and email and subsequently updating the user to specify a different email address.  Updates, removals, and deletions must use the email address (and not the username).
This doesn't fully address #385 because there is a known issue - the UMAPI returns an error when this type of user is created, removed from the org (but not deleted) and added back to the org.  Until this issue is resolved, we'll document it as a known issue in the next release candidate for 2.4.
Update - I made some changes to how these users are created and updated and the "add after remove" issue is resolved.
Fixes #385

Support email-type federated users with different email addresses

---

docs/en/user-manual/advanced_configuration.md
user_sync/rules.py

Reverts adobe-apiplatform/user-sync.py#414
We need to revert this until version 2.12 of umapi-client can be released.  We'll target the feature to v2.4rc3.

Revert "Support email-type federated users with different email addresses"

---

user_sync/app.py
user_sync/config.py

- removed line from app.py default AssertionException block - added a…  …
… separate code block on config.py file to validate this condition.
-- doing a comparison with connectors_config. the value so that, don't have to loop through to make a conditional check "Okta" type

V2 for release 2.4

---

user_sync/connector/directory_ldap.py

iter_users had its signature updated to accept 3 arguments in v2.4 (ea91cb05d9aacbfd874d1be7ad6c63c9d328f9b0).  
This bug was fixed for one of  the other method calls immediately after the commit (b71efa60621a560261808f149247d2178ada7e42),  but this method call was not updated accordingly, causing this behavior.

Fix for #450

---

examples/config files - basic/user-sync-config.yml
user_sync/connector/directory_ldap.py

directory_ldap:
- Account for the case when a user has only 1 group.  LDAPFormatter returns a string instead of a list because first_only is set to true.  We cannot set this to false, because the other attributes depend on it.   We also cannot modify the dn method as it is not part of User Sync.  So, the best solution is to create a one item list in this case.
- If a user has no groups (--users all), LDAPFormatter returns None for the group list -- in this case, we need to immediately return instead of trying to call map() on the NoneType object.
examples\user-sync-config.yml:
- Update the regular expression to escape the "\\" character.  Tested working this way.  Also verified that configapp is able to maintain these fields.  After processing by the app, the following transformation …

#463 fix additional groups bug

---

user_sync/config.py

fixes #468 
I've not tested it, but it should work. I don't think it's practical to have users use the python regex inline modes/modifiers and can't think of a situation where case sensitivity would be required - the only caveat is that I don't believe you can turn case sensitivity back on inline with python.

Exclude Users - Ignore Case

---

user_sync/app.py
user_sync/config.py

Fix for log output when  --adobe-only-user-action is overridden with a cmd line option different than invocation_defaults value

Fix for  #458

---

.build/pre_build.py
.gitignore
Makefile
setup.py
tests/conftest.py
tests/test_config.py
user_sync/app.py
user_sync/cli.py
user_sync/config.py
user_sync/resources/manual_url

Refactor CLI option handling to use [Click](https://click.palletsprojects.com/en/7.x/).  This introduces subcommands - optional pieces of additional functionality to make the Sync Tool more useful as a standalone application.
Specifically, this update implements the following subcommands:
* **sync** - Run user sync (**default**)
* **example-config** - Generate example config files for main config, UMAPI connector and LDAP connector (will prompt for filenames if filename options are not specified - defaults are the usual filenames)
* **docs** - Open the User Manual with the system's default URL handler (generally the default browser)
These are invoked in this manner - 
```sh
$ user-sync [command] [options]
```
e.g.
```sh
$ user-sync example-config --root user-sync-config.yml --umapi …
```

Feature - CLI Refactor

---

user_sync/app.py
user_sync/config.py

Offending code is this:
`
for k, arg_val in self.args.items():
if arg_val is None:
continue
options[k] = arg_val
`
The bool values do not take None as default, they take False, so you won't know if the user forced this value or not in command line unless a default is set in click.options to meet the None requirement.

 Fix for #486

---

user_sync/helper.py

Currently, keys and values are decoded from CSV if the platform is py2.  In doing so, we set the updated value as None.  However, since this transformation doesn't apply to py3, an empty field (,,) in the CSV comes in as "" for py3, and None for py2.  The for loop ought to be adjusted for this.  This essentially means setting empty values to themselves instead of None - this way, CSV data is preserved in both py2 and py3 cases.
```python
row[key.decode(encoding, 'strict')] = val.decode(encoding, 'strict') if val else val
```
A second related issue is that this for loop will throw an exception if there are more fields than column headers for a row.  In python 2, this will throw:
for key, val in six.iteritems(row):
>    row[key.decode(encoding, 'strict')] = val.decode(encoding, 'strict') if …

fix CSV adapter by popping none and not setting empty to none for py2

---

user_sync/helper.py

Same as #493
In py2, I think the row is yielded twice.  Somehow this didn't show up until after the merge.

Looks like yield is releasing double rows for py2 - this works

---

user_sync/sign_sync/app.py
user_sync/sign_sync/connections/sign_connection.py

- Fixed group creation bug. Passed the wrong parameter to the function create_sign_group. When one group needs to be created it attempted to create all user groups. 
- Re-enabled role mapping.
> User Group Admin = Sign Group Admin
> Product Group Admin = Sign Account Admin
> Anything else = Sign Normal User
- Fixed logging bug for role changes. The user role was never updated, so it would always show the opposite roles when logging.

Fixed group creation bug & re-enable user role mapping in Sign

---

setup.py

The ubuntu 3.6 build is failing across the board because the latest jeepney version (released Aug 11, 2019) seems to be broken for ubuntu.  Pex  reports:
wheel.install.BadWheelFile: No expected hash for file 'jeepney-0.4.1.dist-info/tmp/tmp4trcl86h/jeepney-0.4.1/LICENSE'
This fix overrides jeepney to previous version which works on all platforms.

use jeepney 0.4 for py 3

---

user_sync/rules.py

Removed the redundant occurrence of the method normalize_string() from rules.py

Code redundancy fixed on rules.py, line 1319

---

.travis.yml
setup.py

Itertools:
https://travis-ci.org/adobe-dmeservices/user-sync.py/jobs/640559555
**Force old version of itertools for py2 linux to resolve the pex error:**
`**** **Failed to install more-itertools-8.1.0 (**caused by: NonZeroExit("received exit code 1 during execution of `['/home/travis/virtualenv/python2.7.15/bin/python', '-', 'bdist_wheel', '--dist-dir=/tmp/tmpISjMXd']` while trying to execute `['/home/travis/virtualenv/python2.7.15/bin/python', '-', 'bdist_wheel', '--dist-dir=/tmp/tmpISjMXd']`",)
):
stdout:
stderr:
Traceback (most recent call last):
File "<stdin>", line 9, in <module>
File "setup.py", line 5, in <module>
from more_itertools import __version__
ImportError: cannot import name __version__
pex: Failed to install package at /tmp/tmprqWrCA/more-itertools-8.1.0: Failed to …

Centos environment and dependency build issues fix

---

setup.py

Just as soon as the last build issue was resolved, a new python 2 dependency issue showed up.  Very hard to trace the source of this one, but I'm guessing one of the other deps has tried to use a newer version of zipp.  Coincidentally fixing this version for py2 also resolves the more-itertools problem fixed by the last pr.  
I'm not sure if this has anything to do with it, but zipp made a new release like 45 minutes ago (https://pypi.org/project/zipp/#history)
Setting zip==1.1.0 for python 2 resolves the errors.  1.1.0 was the last version supported on python 2, so I'm not sure what might have changed, but I guess some other package is trying to update it.
This was the error:
Successfully installed pex-1.5.3 setuptools-40.9.0 wheel-0.32.3
python .build/pre_build.py
rm -rf dist
pex -v -o …

Python 2 build issue due to Zipp

---

user_sync/connector/directory_okta.py

Added whitelist of builtin Python functions to be available to the eval() function in the okta connector file.
fixes #588

Added whitelist for functions available inside of eval()

---

docs/en/user-manual/advanced_configuration.md
examples/config files - basic/connector-ldap.yml
user_sync/app.py
user_sync/connector/directory_ldap.py

Some OpenLDAP directories do not expect `memberOf` attribute in user-level LDAP request. It now reads memberOf attribute from `user_memberof_format` configuration. It is optional config and accepts `None`. The default value is `{memberOf}`.
#503

Fix for 'invalid attribute type memberOf' at user-level LDAP request

---

.travis.yml
.travis/build-py27.sh
appveyor.yml
setup.py

removed python 2.7

---

user_sync/app.py

Fixes #605.  Dynamic import doesn't work correctly in pyinstaller build if we don't pre-import the connectors.

Fix for #605

---

tests/test_post_sync.py
user_sync/post_sync/connectors/sign_sync/__init__.py

Fixes issue #632 
The `update_sign_users` method in the SignConnector was skipping sign users if their email had different casing from the UMAPI users. Since the Sign API returns all lowercase emails, this was causing unwanted skips. For example, the loop would start with a sign user "user@example.com." Then it would look up that email from the UMAPI users dictionary. If the corresponding UMAPI user was "User@example.com," there would be no match and the should_sync method would be passed None for the Sign user, thus returning false, thus skipping the rest of the update.
The fix in SignConnector was just a `.lower()`. This PR also includes a unit test which checks the lookup of a Sign user against a UMAPI user with an email address that is identical except for a capital letter.

Sign post-sync bug fix - email casing difference between umapi and sign users

---

.build/.appveyor/build.ps1

*  Only archive artifacts if commit is tagged
Example
* No tag: https://ci.appveyor.com/project/adorton/user-sync-py/builds/35543497/job/9ktx2i5dpofl1lga#L672
* Tag: https://ci.appveyor.com/project/adorton/user-sync-py/builds/35543545/job/k8kjurmiesl2qxfk#L669
Fixes: #642

Archive only tagged builds on appveyor

---

docs/en/success-guide/scheduling.md

Updating the scheduling documentation to include some additional guidelines to encourage clients to choose a sync time that does not overlap with the majority of clients.

Add additional guidelines to the scheduling page

---

user_sync/connector/directory_ldap.py

* In the pre-2.8 version of LDAP3 library, binding TLS on Secure LDAP will silently error out but in 2.8+, it will raise an exception and causing it to throw ```automatic start_tls befored bind not successful```. As a solution, if the connection is SSL aka LDAPS, there is no need for TLS before Bind since it already encrypted.
* Set Host to ldaps://
* Set Require_TLS_Cert: True
(Since TLS automatically establishes on bind, this should not throw ```automatic start_tls befored bind not successful``` error anymore.)
* Set Host to ldap://
* Set Require_TLS_Cert: True
( This will force the connection to start_tls before binding on unsecured LDAP (389) )
Fixes #656

Bug fix: Prevent start_tls before Bind on LDAPS Connection

---

user_sync/connector/directory_ldap.py

By default the ldap3 library attempts to bind against the service principal for the domain you attempted to connect to. If your target LDAP service uses a round-robin DNS, it’s likely that the hostname you connect to won’t match. This cause it to throw the following error:
```LDAP connection failure: SSPI: InitializeSecurityContext: The specified target is unknown or unreachable```
In this case, you can either specify Domain Controller hostname or force the library to do a reverse DNS lookup.
This PR includes the fix to do a reverse DNS lookup automatically when using Kerberos Authentication Method by simply pass True as the first element in sasl_credentials to do a reverse DNS lookup.
There is no additional configuration end-user have to do. This solution supported Domain Controller FQDN …

Support Specifying Domain Name for Kerberos Authentication.

---

examples/config files - basic/connector-umapi.yml

The expected string value should be:
secure_client_id_key: umapi_client_id 
Incorrect value was:
secure_client_id
Fixes #639

Typo in connector-umapi.yml

---

examples/config files - basic/user-sync-config.yml

Remove the extra leading space on commented out auto group create options.  It's been driving me crazy that to make it work you need to both uncomment AND remove a leading space, unlike everything else in the file!

Fix commented indentation for auto group create

---

docs/en/user-manual/deployment_best_practices.md
examples/config files - basic/connector-umapi.yml
examples/config files - basic/user-sync-config.yml
user_sync/app.py
user_sync/config.py
user_sync/connector/directory_adobe_console.py
user_sync/connector/umapi.py
user_sync/post_sync/connectors/sign_sync/__init__.py
user_sync/post_sync/connectors/sign_sync/client.py

Replacement for #608 because it was easier to rewrite than modify that PR further
- Move to cover all https connections, not just UMAPI since it doesn't make sense to apply this setting on a per-connector basis. Setting lives in user-sync-config invocation defaults
- Doesn't work with Okta - since okta's requests are external
- Disables verbose warning for every request, and instead displays warning at start of sync
- Raises error with info to switch to new method if found in connector-umapi
- Backwards compatible - existing umapi server config option will be respected
The option is injected in config.py - while I don't like this method of implementation, I think it is the most reasonable in terms of end user experience.  Otherwise, the ssl_cert_verify key would need to be present and …

Ssl cert verify v3

---

docs/en/user-manual/advanced_configuration.md

Add documentation for two-step lookup to the **Advanced Configuration** section of the UST manual.
fixes #590

Document two-step lookup

---

user_sync/config.py

Keyrings are now reported as type Chainer backend when pulling keyring.get_keyring() on windows, instead of the WindowsVault.  
Code updated to use chainer instead of bypassing for cryptfile in this case.
Tested on windows and ubuntu (not yet centos)
Fixes: https://github.com/adobe-apiplatform/user-sync.py/issues/708

Fix keyring misidentification issue

---

README.md

* Service account creation official docs link for User Management API was broken.  Corrected to current service account integration page in official docs.
* Confirmed link went to non-broken page
Fixes #733

Fixed broken link to official docs

---

user_sync/rules.py

*  because `self.process_strays` returns ([],{}), then there are no other commands to execute in `self.execute_commands`, hence after critical log line no other process continues and Summary is shown
the fix is to continue returning the existing list of commands
* run with same ldap changes as stated in the issue #744
Fixes #744

continue create actions after max remove limit reached

---

docs/en/user-manual/advanced_configuration.md
user_sync/engine/umapi.py

* When `uses_business_id` is enabled, just override the identity type without requiring a primary target
* Update docs
* Sync to a T2E trustee with no primary target
Fixes #767

Simplify identity type override for ESM trustees

---

user_sync/error.py

This PR adds a new class to error.py that is a subclass of Python's built-in DeprecationWarning. It will print/log any future deprecation warning messages wrapped in ANSI control codes to make the text yellow in a console window.
No additional tests were written for this PR.
Fixes #757

Custom deprecation warning for User Sync Tool

---

user_sync/engine/sign.py

* changed the logic so that the Sign extraction is done first, then the Sign connection
* have 7k or more accounts in Sign Dashboard and default 2min timeout for ldap connection
* run UST for Sign sync and have the Sign extraction take longer than the ldap connection expiration time
* UST should not throw the error anymore 
Fixes #790

Update sign.py - fixes #790

---

user_sync/connector/directory_okta.py

If the host name is formatted incorrectly in connector-okta.yml, it triggers an unhandled exception. This PR adds a block of code to handle the particular exception that gets triggered in that case (namely `requests.exceptions.SSLError`) and raises an AssertionException instead.
I did not write any new tests for this PR.
Fixes #601

Add except block for SSLError in Okta connector
